name: Test

on: 
  workflow_dispatch:
  pull_request:
  push:
    branches: main

jobs:
  test:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: Cyberbeni/install-swift-tool@v3
        with:
          url: https://github.com/tuist/xcbeautify
          version: '*'
      - run: |
          set -o pipefail
          swift test 2>&1 | xcbeautify
